[fix] 演習の実装
KiuchiKazuki/RNStudy_Practice_2021-05-28_HelloWorld pull request #1
Opened 2021-06-01 08:41 UTC by KiuchiKazuki

2021-06-01 09:06 UTC, okumura-sse0218 requested changes

2021-06-01 09:11 UTC, KiuchiKazuki commented on App.js
> +    var cnt = 0;
これ、Kolinの時の癖でやっちゃうんですよね。
修正します。

2021-06-01 09:12 UTC, KiuchiKazuki commented on App.js
> +    Alert.alert("Count!", "Button was pressed " + cnt + " times.", null, null);
多分勉強会でやってないんで、補足した上で修正します。

2021-06-02 02:46 UTC, okumura-sse0218 requested changes

2021-06-02 02:46 UTC, okumura-sse0218 commented on README.md
> +    // count++;でも暗黙的型変換されるので動くが、バグになりやすいのであまり使用し内容が良い
@KiuchiKazuki  指摘漏れすみません。
>あまり使用し内容が良い
こっちもtypoでした。

あとコードも古いので、App.js参照みたいな感じで書いとけば良いのではないでしょうか。

2021-06-02 02:57 UTC, KiuchiKazuki commented on README.md
> +    // count++;でも暗黙的型変換されるので動くが、バグになりやすいのであまり使用し内容が良い
ファイルを行き来すると見る側が面倒だと思うので、コードを新しくしました。

2021-06-02 04:11 UTC, merged